import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { type ReactNode } from 'react'
import Theme from '@/theme'

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
      <html lang="en">
        <body className={roboto.className}>
            <Theme>
                {children}
            </Theme>
        </body>
      </html>
  )
}
