import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { type ReactNode } from 'react'

type Props = {
    children: ReactNode
}

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Props) {
  return (
      <html lang="en">
        <body className={roboto.className}>
            {children}
        </body>
      </html>
  )
}
