import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { type ReactNode } from 'react'
import { CssBaseline } from "@mui/material";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
      <html lang="en">
        <body className={roboto.className}>
          <AppRouterCacheProvider>
              <CssBaseline />
              {children}
          </AppRouterCacheProvider>
        </body>
      </html>
  )
}
